VERSION 0.7
IMPORT ../.. AS root
IMPORT ../../packages/repository AS repository

all:
  BUILD root+prune --app='api'
  BUILD root+build --app='api'
  BUILD repository+migrator

  FROM root+final-image --app='api'
  COPY repository+migrator/migrator .
  DO root+FINALIZE_APP --app='api'

  CMD [ \
    "node", \
    "-r", "ts-node/register", \
    "-r", "tsconfig-paths/register", \
    "--max-old-space-size=256", \
    "/app/apps/api/dist/main.js" \
  ]
  SAVE IMAGE cyborch/toottail-api:1.1.0
